export const FETCHING_TRACKS_REQUESTED = "FETCHING_TRACKS_REQUESTED";
export const FETCHED_TRACKS = "FETCHED_TRACKS";
export const FETCHING_TRACKS_FAILED = "FETCHING_TRACKS_FAILED";
export const SEARCH_TRACKS_SUCCESS = "SEARCH_TRACKS_SUCCESS";
export const SEARCH_TRACKS_FAILED = "SEARCH_TRACKS_FAILED";
export const SEARCHING = "SEARCHING";
